github_username: tkchu
github_projectname: blog.tkchu.me

title: 游戏炼金术
description: >
  理解-分解-再构造。对现有的游戏进行拆分，探索现有设计的优劣之处，总结可能的规律。
author: 楚天阔

#twitter_username: tkchushbm # twitter
zhihu_username: tkchu # zhihu
steam_username: tkchu # steam 该项需要在steam上编辑个人资料，指定自定义URL
bilibili_id: 2395115
duoshuo_username: tkchushbm # 多说

use_rss: yes
baseurl: /
url: http://blog.tkchu.me

cdnurl: http://ohe7bqlax.bkt.clouddn.com
